# These are supported funding model platforms

github: mr-september
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: mrseptember6969
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: mr-september
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: ["https://www.paypal.com/donate/?hosted_button_id=WFXL2T42BBCRN"]
